SUPABASE_URL="https://vwibdnfvjhlkhtguzagf.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aWJkbmZ2amhsa2h0Z3V6YWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1ODQ3NTYsImV4cCI6MjEwMzE2MDc1Nn0.-hqLcV0iT99Q0zVoyL4tZeK1kk6k3JDYTTMw0oVXVMQ"
